### PR TITLE
Mysql backend

### PR DESCRIPTION
**Pull request by shridarpatil**

### CODE REVIEW

**Comment by rmehta** [comment]
Awesome 👍 

Lets commonify some of the code so that there is a generic backend.

Make it object oriented?

**Comment by rmehta** [comment]
@shridarpatil added baseclass for database

see: https://github.com/frappe/frappejs/blob/master/backends/sqlite.js

also add tests for the mariadb backend.

**Comment by shridarpatil** [comment]
will make the changes and add tests.

**Comment by rmehta** [comment]
@shridarpatil rebase when you pull / merge in your branch

**Comment by shridarpatil** [comment]
ok sure

**Pull request closed without merging**
