### PR TITLE
Add functions required to connect two peers and transfer data between them.

### PR DESCRIPTION
**Pull request by anto-christo**
This PR initializes the WebRTC module and does the following:
1. Initialize peer connection both at host and client side.
2. Set local description at host.
3. Generate offer from host.
4. Set local and remote description at client.
5. Generate answer from client.

# Usage

- Host Side
```
const WebRTC = require(frappejs/webrtc/webrtc);

const webRTC = new WebRTC();

webRTC.createOffer().then(offer => {
    //RTCPeerConnection initialized at host
    //offer generated
}); 
```

- Client Side
```
const WebRTC = require(frappejs/webrtc/webrtc);

const webRTC = new WebRTC();

webRTC.createAnswer(offer).then(answer => {
    //RTCPeerConnection initialized at client
    //answer generated
}); 
```
@rmehta @netchampfaris , kindly review. Thank you.

### CODE REVIEW

**Comment by rmehta** [comment]
looks good, how do we connect to a specific peer?

**Comment by anto-christo** [comment]
In order to connect to a specific client, we need to transfer the 'Offer' generated by the host to the intended client and the 'Answer' from client to the host. This can be done by using any 'signalling mechanism'. WebRTC doesn't define any standard for signalling in order to provide flexibility to the developers. So the above code only takes of generating the 'Offer' and 'Answer'.

For testing the above code, I used sockets as the signalling mechanism. The host creates a room and the clients join that room, the host then broadcasts it's 'Offer' to all the clients in the room via sockets. ( We're planning to define a standard signalling mechanism within the wrapper once enough functions are added in the wrapper to do data transmission).

This is based on my understanding of WebRTC, please do correct me if I'm wrong.

**Comment by rmehta** [comment]
Let create the signalling mechanism and make the complete feature that gets usable. Even a end-to-end connector with a basic singaling mechanism and UI is a good first cut. Should be do-able.

**Comment by anto-christo** [comment]
Working on it !

**Comment by anto-christo** [comment]
# Updated PR

Have updated the PR to include functions to connect two peers and transfer data between them.

# Usage
### Initialize WebrRTC.
```
const WebRTC = require('frappejs/webrtc/webrtc');
var webRTC = new WebRTC();
```
### Connect to a peer

Signalling mechanism is entirely handled by Socket.io. The two peers need to be in the same room to be able to transfer data with each other. We can have multiple such rooms with host-client pair.

```webRTC.initConnection(roomName);```

`webRTC.initConnection` is responsible for connecting two peers. It takes in the 'room' name as the parameter. The room name can be considered as an identifier needed for connecting both the peers, it can either be automatically generated or manually entered based on the application. The only thing is we need to pass the same room name so that the two peers can communicate with each other.

### Send data
` webRTC.sendData(dataToSend);`

Call the `webRTC.sendData` function to transfer data to the connected peer. Pass the data that has to be send as the parameter to the function.  

### Receive data
```
webRTC.onDataReceive = data => {
    //do something with 'data'
};
```
`webRTC.onDataReceive` is an event handler that is triggered when a data is received from the connected peer.

# Example
https://github.com/anto-christo/frappejs-webrtc-example
Have kept the UI very very minimal and basic. It demonstrates a simple one-to-one chat using the above mentioned functions.

@rmehta @netchampfaris , kindly let know if any modifications required.

**Comment by anto-christo** [comment]
# Updated PR

Have updated the PR to include functions to connect two peers and transfer data between them.

# Usage
### Initialize WebrRTC.
```
const WebRTC = require('frappejs/webrtc/webrtc');
var webRTC = new WebRTC();
```
### Connect to a peer

Signalling mechanism is entirely handled by Socket.io. The two peers need to be in the same room to be able to transfer data with each other. We can have multiple such rooms with host-client pair.

```webRTC.initConnection(roomName);```

`webRTC.initConnection` is responsible for connecting two peers. It takes in the 'room' name as the parameter. The room name can be considered as an identifier needed for connecting both the peers, it can either be automatically generated or manually entered based on the application. The only thing is we need to pass the same room name so that the two peers can communicate with each other.

### Send data
` webRTC.sendData(dataToSend);`

Call the `webRTC.sendData` function to transfer data to the connected peer. Pass the data that has to be send as the parameter to the function.  

### Receive data
```
webRTC.onDataReceive = data => {
    //do something with 'data'
};
```
`webRTC.onDataReceive` is an event handler that is triggered when a data is received from the connected peer.

# Example
https://github.com/anto-christo/frappejs-webrtc-example
Have kept the UI very very minimal and basic. It demonstrates a simple one-to-one chat using the above mentioned functions.

@rmehta @netchampfaris , kindly let know if any modifications required.

**Comment by rmehta** [comment]
@anto-christo can we have a UI for setting up the rooms? Also share a GIF animation on how this works!

**Pull request closed without merging**
